version: 2

jobs:
  build:
    docker:
      - image: buildpack-deps:jammy
    steps:
      - checkout
      - run:
          name: Install SciPy
          command: apt-get update; apt-get install -y time python-numpy python-scipy;
      - run:
          name: Install GCC-9
          command: apt-get install -y g++-9 gcc-9 libc6-dev libc-dev make;
      - run:
          name: Install Clang
          command: apt-get install -y clang libc++-dev clang-format
      - run:
          name: Install Eigen
          command: bash scripts/install_eigen.sh
      - run:
          name: Install Sciplot
          command: bash scripts/install_sciplot.sh
      - run:
          name: Test with GCC
          command: make COMPILER=gcc clean_test test
      - run:
          name: Test with Clang
          command: make COMPILER=clang clean_test test
      - run:
          name: Run examples with GCC
          command: bash scripts/test_examples.sh gcc
      - run:
          name: Run examples with Clang
          command: bash scripts/test_examples.sh clang

workflows:
  version: 2
  build-test:
    jobs:
      - build
