version: 2

jobs:
  build:
    docker:
      - image: buildpack-deps:jammy
    steps:
      - checkout
      - run:
          name: Requirements
          command: apt-get install lsb-release wget software-properties-common gnupg
      - run:
          name: Install SciPy
          command: apt-get update; apt-get install -y time python3-numpy python3-scipy;
      - run:
          name: Install GCC-10
          command: apt-get install -y g++-10 gcc-10 libc6-dev libc-dev make;
      - run:
          name: Install Clang-19
          command: wget -qO- https://apt.llvm.org/llvm.sh | bash -s -- 19
      - run:
          name: Install Eigen
          command: bash scripts/install_eigen.sh
      - run:
          name: Install Sciplot
          command: bash scripts/install_sciplot.sh
      - run:
          name: Test with GCC
          command: make COMPILER=gcc clean_test test
      - run:
          name: Test with Clang
          command: make COMPILER=clang clean_test test
      - run:
          name: Run examples with GCC
          command: bash scripts/test_examples.sh gcc
      - run:
          name: Run examples with Clang
          command: bash scripts/test_examples.sh clang

workflows:
  version: 2
  build-test:
    jobs:
      - build
